add subdire to cat composer

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -40,7 +40,7 @@ cache_dir=$2/php
 mkdir -p "$cache_dir"
 env_dir=${3:-} # Anvil has none
 bp_dir=$(cd $(dirname $0); cd ..; pwd)
-app_subdir=application
+app_subdir=application/
 
 # convenience functions
 source $bp_dir/bin/util/common.sh
@@ -73,23 +73,23 @@ fi
 export COMPOSER_LOCK=$(basename "$COMPOSER" ".json")".lock" # replace .json with .lock if it exists, append .lock otherwise
 
 # a bunch of sanity checks first
-if [[ -s "$app_subdir/$COMPOSER" ]]; then
-    cat "$app_subdir/$COMPOSER" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER'; make sure it's valid!"
-    if [[ ! -f "$app_subdir/$COMPOSER_LOCK" ]]; then
-        cat "$app_subdir/$COMPOSER" | python -c 'import sys, json; sys.exit(bool(json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your '$COMPOSER' lists dependencies inside 'require',
+if [[ -s "$app_subdir$COMPOSER" ]]; then
+    cat "$app_subdir$COMPOSER" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER'; make sure it's valid!"
+    if [[ ! -f "$app_subdir$COMPOSER_LOCK" ]]; then
+        cat "$app_subdir$COMPOSER" | python -c 'import sys, json; sys.exit(bool(json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your '$COMPOSER' lists dependencies inside 'require',
 but no '$COMPOSER_LOCK' was found. Please run 'composer update' to
 re-generate '$COMPOSER_LOCK' if necessary, and commit it into your
 repository. For more information, please refer to the docs at
 https://devcenter.heroku.com/articles/php-support#activation"
     else
-        cat "$app_subdir/$COMPOSER_LOCK" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER_LOCK'; make sure it's valid!"
-        if [[ $(cat "$app_subdir/$COMPOSER_LOCK" | python -c 'import sys, json; print json.load(sys.stdin)["hash"]' 2> /dev/null) != $(md5sum "$app_subdir/$COMPOSER" | cut -d " " -f1) ]]; then
+        cat "$app_subdir$COMPOSER_LOCK" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER_LOCK'; make sure it's valid!"
+        if [[ $(cat "$app_subdir$COMPOSER_LOCK" | python -c 'import sys, json; print json.load(sys.stdin)["hash"]' 2> /dev/null) != $(md5sum "$app_subdir$COMPOSER" | cut -d " " -f1) ]]; then
             warning "Your '$COMPOSER_LOCK' is not up to date with the latest
 changes in '$COMPOSER'. To ensure you are not getting stale
 dependencies, run 'composer update' on your machine and commit
 any changes to Git before pushing again."
         fi
-        cat "$app_subdir/$COMPOSER_LOCK" | python -c 'import sys, json; l = json.load(sys.stdin); sys.exit(not(l["minimum-stability"] == "stable"));' 2> /dev/null || warning "Your '$COMPOSER' contains a non-'stable' setting
+        cat "$app_subdir$COMPOSER_LOCK" | python -c 'import sys, json; l = json.load(sys.stdin); sys.exit(not(l["minimum-stability"] == "stable"));' 2> /dev/null || warning "Your '$COMPOSER' contains a non-'stable' setting
 for 'minimum-stability'. This may cause the installation of
 unstable versions of runtimes and extensions during this deploy.
 It is recommended that you always use stability flags instead,
@@ -97,7 +97,7 @@ even if you have 'prefer-stable' enabled. For more information,
 see https://getcomposer.org/doc/01-basic-usage.md#stability"
     fi
 else
-    if [[ ! -f "$app_subdir/$COMPOSER" ]]; then
+    if [[ ! -f "$app_subdir$COMPOSER" ]]; then
         warning "No '$COMPOSER' found.
 Using 'index.php' to declare PHP applications is considered legacy
 functionality and may lead to unexpected behavior."
@@ -282,9 +282,9 @@ if [[ "$engine" == "php" ]]; then
     status "Enabling PHP extensions..."
 
     exts=()
-    if [[ -f "$app_subdir/$COMPOSER_LOCK" ]]; then
-        exts=($(cat "$app_subdir/$COMPOSER_LOCK" | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
-        ext_source="$app_subdir/$COMPOSER_LOCK"
+    if [[ -f "$app_subdir$COMPOSER_LOCK" ]]; then
+        exts=($(cat "$app_subdir$COMPOSER_LOCK" | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
+        ext_source="$app_subdir$COMPOSER_LOCK"
     fi
     for ext in "${!exts[@]}"; do # loop over keys in case the array is empty or else it'll error out
         install_ext "${exts[$ext]}" $ext_source
@@ -313,8 +313,8 @@ fi
 # tail to get rid of outdated version warnings (Composer sends those to STDOUT instead of STDERR)
 composer --version 2> /dev/null | tail -n 1 | indent
 
-composer_vendordir=$app_subdir/$(composer config vendor-dir -d $app_subdir/ 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
-composer_bindir=$app_subdir/$(composer config bin-dir -d $app_subdir/ 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
+composer_vendordir=$app_subdir$(composer config vendor-dir -d $app_subdir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
+composer_bindir=$app_subdir$(composer config bin-dir -d $app_subdir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
 
 echo "get composer subdir $composer_vendordir"
 
@@ -366,7 +366,7 @@ cat "$COMPOSER" | python -c 'import sys,json; sys.exit(not json.load(sys.stdin))
 composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your '$COMPOSER' requires 'heroku/heroku-buildpack-php'.
 This package may only be used as a dependency in 'require-dev'!"
 
-if cat "$COMPOSER" | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
+if cat "$app_subdir$COMPOSER" | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
     status "Running 'composer compile'..."
     composer run-script --no-dev --no-interaction compile 2>&1 | indent
 fi
